[versions]
coreKtx = "1.7.0"
coreSplashScreen = "1.0.0-beta02"
material = "1.5.0"
playServicesTasks = "18.0.1"
playServicesAds = "20.5.0"
playCoreKtx = "1.8.1"
jUnit5 = "5.8.2"
assertJ = "3.22.0"
compose = "1.1.1"
activityCompose = "1.4.0"
constraintLayoutCompose = "1.0.0-rc02"
firebase = "30.0.1"
timber = "5.0.1"
hilt = "2.41"
coroutines = "1.6.1"
mockK = "1.12.3"
gradle = "7.1.3"
kotlin = "1.6.10"
jUnit5Plugin = "1.8.2.0"
googleService = "4.3.10"
crashlyticsGradle = "2.8.1"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashScreen" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasks" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-core-ktx = { module = "com.google.android.play:core-ktx", version.ref = "playCoreKtx" }

# JUnit5
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit5" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertJ" }

# compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", name = "runtime-livedata", version.ref = "compose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayoutCompose" }

# firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

mockk = { module = "io.mockk:mockk", version.ref = "mockK" }

# Gradle
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-junit5-gradle = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "jUnit5Plugin" }
google-services-gradle = { module = "com.google.gms:google-services", version.ref = "googleService" }
hilt-android-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlyticsGradle" }

[bundles]
compose = [
    "compose-ui",
    "compose-material",
    "compose-ui-tooling",
    "compose-runtime-livedata",
    "activity-compose",
    "constraintlayout-compose"
]
