[versions]
jUnit5 = "5.8.2"
compose = "1.4.3"
hilt = "2.44"
coroutines = "1.6.1"
flipper = "0.164.0"
kotlin = "1.8.10"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version = "1.7.0" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0" }
material = { module = "com.google.android.material:material", version = "1.5.0" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version = "18.0.1" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version = "20.5.0" }
play-core-ktx = { module = "com.google.android.play:core-ktx", version = "1.8.1" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }

# JUnit5
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit5" }
assertj-core = { module = "org.assertj:assertj-core", version = "3.22.0" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", name = "runtime-livedata", version.ref = "compose" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.0-rc02" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.5.3" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "31.4.0" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

mockk = { module = "io.mockk:mockk", version = "1.12.3" }

profile-installer = { module = "androidx.profileinstaller:profileinstaller", version = "1.2.0" }

# Gradle
gradle = { module = "com.android.tools.build:gradle", version = "7.4.2" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-junit5-gradle = { module = "de.mannodermaus.gradle.plugins:android-junit5", version = "1.8.2.0" }
google-services-gradle = { module = "com.google.gms:google-services", version = "4.3.14" }
hilt-android-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.8.1" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "11.0.0" }
dependency-guard = { module = "com.dropbox.dependency-guard:dependency-guard", version = "0.4.3" }

# Flipper
flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
soloader = { module = "com.facebook.soloader:soloader", version = "0.10.4" }

[bundles]
compose = [
    "compose-ui",
    "compose-material",
    "compose-ui-tooling",
    "compose-runtime-livedata",
    "activity-compose",
    "constraintlayout-compose",
    "navigation-compose"
]
