# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "upload debug apk"
  lane :uploadDebug do
    gradle(
      task: "clean assemble",
      build_type: "Debug"
    )
    firebase_app_distribution(
      service_credentials_file: "./fastlane/firebase-app-distributor-services.json",
      app: "1:752769857307:android:d87190c8e33efdb93285be",
      groups: "tester"
    )
  end
end
