name: Cleanup stale branch

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  remove-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          exempt-branches-regex: "^(main|APPDEV-.*)$"
          days-before-branch-stale: 1
          days-before-branch-delete: 1
