name: Cleanup stale branch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  remove-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.1.2
        with:
          exempt-branches-regex: "^(main|APPDEV-.*|dependabot.*)$"
          days-before-branch-stale: 14
          days-before-branch-delete: 1
