name: Firebase App Distributor

on:
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Create firebase-app-distribution-services.json
        run: echo '${{ secrets.FIREBASE_APP_DISTRIBUTOR_SERVICES_JSON }}' > ./firebase-app-distributor-services.json

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Check Test
        run: ./gradlew testDebugUnitTest

      - name: Deploy to Firebase App Distributor
        run: ./gradlew appDistributionUploadDebug
