name: Firebase App Distributor

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Create firebase-app-distribution-services.json
        run: echo '${{ secrets.FIREBASE_APP_DISTRIBUTOR_SERVICES_JSON }}' > ./firebase-app-distributor-services.json

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Deploy to Firebase App Distributor
        run: ./gradlew appDistributionUploadDebug
