name: Play Store

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Clean Managed Devices
        run: ./gradlew cleanManagedDevices --unused-only

      - name: Generate Baseline Profile
        run: |
          ./gradlew :benchmark:pixel2Api31BenchmarkAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile -Dorg.gradle.workers.max=4

      - name: Move & Rename Baseline Profiles
        run: |
          mv -f benchmark/build/outputs/managed_device_android_test_additional_output/benchmark/pixel2Api31/ExampleStartupBenchmark_startup-baseline-prof.txt app/src/main/baseline-prof.txt

      - name: Extract existing version code
        run: |
          version_code=$(grep "VERSION_CODE" ./build-logic/convention/src/main/java/plugin/AndroidApplicationConventionPlugin.kt | awk '{print $5}')
          version_code=$((version_code + ${GITHUB_RUN_NUMBER}))
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV

      - name: Change version code
        run: |
          echo "${{ env.VERSION_CODE }}"
          sed -i "" "s/VERSION_CODE = [0-9]*/VERSION_CODE = ${{ env.VERSION_CODE }}/g" ./build-logic/convention/src/main/java/plugin/AndroidApplicationConventionPlugin.kt

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store (INTERNAL)
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJson: service_account.json
          packageName: com.beok.runewords
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: whatsnew/
